version: '3.8'

services:
  db:
    image: postgres:17.6
    restart: always
    environment:
      POSTGRES_DB: copperline
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: copperline-api
    environment:
      NODE_ENV: production
      DATABASE_URL: "postgresql://postgres:1234@db:5432/copperline"
    ports:
      - "3000:3000"
    restart: always

volumes:
  postgres_data: